### ISSUE TITLE
Can't install package via git URL

### ISSUE THREAD

**Issue by andreiagmu** [stonesheltergames/Unity-GUID#2]
@Xriuk @jorbascrumps 
I'm using Unity 2021.3.18f1

I tried following the install instructions, by entering `https://github.com/stonesheltergames/Unity-GUID.git` in Package Manager's `Add package from git URL` option. But this makes Unity throw the following errors in the console:

```
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/stonesheltergames/Unity-GUID.git]:
  [https://github.com/stonesheltergames/Unity-GUID.git] does not point to a valid package. No package manifest was found. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

```
[Package Manager Window] Error adding package: https://github.com/stonesheltergames/Unity-GUID.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

**Comment by andreiagmu** [comment]
I think moving the `package.json` and `package.json.meta` files to the root folder of the repository should fix the issue.

**Comment by andreiagmu** [comment]
As of now, I was able to install the package via Package Manager by entering this URL in `Add package from git URL` option:

`https://github.com/stonesheltergames/Unity-GUID.git?path=/Assets/StoneShelter`

**Comment by Xriuk** [comment]
I guess at this point the Assets folder could be deleted and StoneShelter moved at the root, since this started as a cloneable repo instead of a package.
And also the package definitions should be moved to the root, you are welcome to submit a PR if you wish.

**Comment by andreiagmu** [comment]
Thanks for the info, I'm preparing a PR right now. :)

Based on the common structure of other Package Manager git packages, I think even the "StoneShelter" folder could be deleted, then the GUID.cs and Editor folder would be directly located at the root (or inside a [root]\Scripts folder).

I'm not sure, but maybe having that StoneShelter folder inside this package could cause conflicts with other packages that could also have a StoneShelter folder - I guess the usual Package Manager folder structure makes that folder redundant.

**Comment by Xriuk** [comment]
> Thanks for the info, I'm preparing a PR right now. :)
> 
> Based on the common structure of other Package Manager git packages, I think even the "StoneShelter" folder could be deleted, then the GUID.cs and Editor folder would be directly located at the root (or inside a [root]\Scripts folder).
> 
> I'm not sure, but maybe having that StoneShelter folder inside this package could cause conflicts with other packages that could also have a StoneShelter folder - I guess the usual Package Manager folder structure makes that folder redundant.

True
