### ISSUE TITLE
Can't add GUID component to any GameObject/prefab (possibly because of missing .asmdefs)

### ISSUE THREAD

**Issue by andreiagmu** [stonesheltergames/Unity-GUID#3]
@Xriuk @jorbascrumps
I'm using Unity 2021.3.18f1

After I installed this package via Package Manager (using the URL I mentioned in #2), it didn't compile as it should in my project.
There are no errors in the Console, but the GUID component doesn't appear in the `Add Component` menu.
And there's no other way to add the GUID component to my GameObjects/prefabs (no new MenuItem appears at the top bar; directly dragging the GUID component to my GameObject doesn't work).

This issue may have been caused by the fact this package doesn't include any .asmdef files.
Every other `Package Manager` package I have installed here in my projects (including git packages) always has its own .asmdefs.

This is missing an `UnityGUID.asmdef` in the "Unity GUID" folder, and a `UnityGUID.Editor.asmdef` in the "Unity GUID\Editor" folder.
`UnityGUID.Editor.asmdef` should be an _Editor-only assembly_.

Some code inside GUID.cs *may* also need to be wrapped inside `#if UNITY_EDITOR` preprocessor directives, to avoid build errors.

**Comment by Xriuk** [comment]
Yep, I guess in GUID.cs the Editor using directives at the top should be wrapped in #if, everything else should be already wrapped. We're open for PRs
