### ISSUE TITLE
Installing package from git missing assembly reference

### ISSUE THREAD

**Issue by BurritoBushido** [stonesheltergames/Unity-GUID#5]
Library\PackageCache\com.stoneshelter.guid@178bde625e\Scripts\GUID.cs(34,58): error CS1061: 'GUID[]' does not contain a definition for 'Where' and no accessible extension method 'Where' accepting a first argument of type 'GUID[]' could be found (are you missing a using directive or an assembly reference?)

Adding System.Linq makes the error go away but the StoneShelter namespace isn't available to use.

**Comment by andreiagmu** [comment]
I just tried updating to the latest commit [@178bde6](https://github.com/stonesheltergames/Unity-GUID/commit/178bde625ef433221ac585da395497e26ce435dc), and I'm having the same error.

For now, I reverted to the previous working commit: https://github.com/stonesheltergames/Unity-GUID/commit/bb6a5359cc8bfd8889a7a214309885ac1506e73d

**Comment by dvandersluis** [comment]
I got this error too when trying to install via git in the Package Manager. Is there any fix there?

Update: you can add a specific commit to the URL being installed in the package manager: 
https://github.com/stonesheltergames/Unity-GUID.git#bb6a5359cc8bfd8889a7a214309885ac1506e73d

**Comment by Xriuk** [comment]
Hello, sorry for the very late reply but this repo is not actively monitored. This should be fixed in the lastest commit.
